# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kate', '0002_auto_20170320_1322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='kate_person',
        ),
    ]
